# Branch protection rules

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - french-check
      required_pull_request_reviews:
        dismissal_restrictions:
          users: []
          teams: []
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      restrictions:
        users: []
        teams: []
        apps: []
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - french-check
      required_pull_request_reviews:
        dismissal_restrictions:
          users: []
          teams: []
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      restrictions:
        users: []
        teams: []
        apps: []
      enforce_admins: false
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false 