stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# NPM dependencies cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Build job
build:
  stage: build
  image: node:18-slim
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

# Simplified test job (with mocks)
test:simplified:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t coc-vue-test .
    - docker run --rm coc-vue-test ./scripts/test/runners/run-simplified-tests.sh

# Full test job (optional, may fail)
test:full:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t coc-vue-test .
    - docker run --rm coc-vue-test ./scripts/run-tests-with-timeout.sh
  allow_failure: true

# Deployment job (example)
deploy:
  stage: deploy
  image: node:18-slim
  script:
    - echo "Deploying coc-vue extension"
    - npm pack
  artifacts:
    paths:
      - "*.tgz"
  only:
    - tags
    - master
