version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-results:/app/test-results
    command: ./scripts/docker-run-tests.sh
    environment:
      - MOCK_NEOVIM=true
      - NODE_ENV=test
      - CI=true

  # Service for running full tests (may fail)
  test-full:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-results:/app/test-results
    command: ./scripts/run-tests-with-timeout.sh
    environment:
      - NODE_ENV=test
      - CI=true
